newfunctions
samardhk/mealplanner pull request #3
Opened 2024-01-19 09:25 UTC by samardhk

added calorie function that spits out macros as well.

2024-01-21 03:02 UTC, atul-jalan requested changes

2024-01-21 03:02 UTC, atul-jalan commented on calculation.js
> +    var age = document.getElementById('age').value;
These should all be either 'const' or 'let'.

2024-01-21 03:02 UTC, atul-jalan commented on calculation.js
> +function TDEE() {
what does TDEE mean?

2024-01-21 03:02 UTC, atul-jalan commented on calculation.js
> +    var totalInches = (+feet * 12) + +inches;
what does `+feet` mean?

2024-01-21 03:02 UTC, atul-jalan commented on calculation.js
> +    var bmr = (10 * weightInKilos) + (6.25 * heightInCM) - (5 * age) + 5;
Generally in programming, we declare variables for constant values.

So at the top of the `calculation.js` file, you'd declare the following:

```
const CENTIMETERS_PER_INCH = 2.54;
const KILOS_PER_POUND = .453592;
...
```

And then the actual calculation would be:

```
const heightInCM = totalInches * CENTIMETERS_PER_INCH
...
```

2024-01-21 03:02 UTC, atul-jalan commented on calculation.js
> +    var sup = 1.9;
I would delcare this as a constant at the top of the `calculation.js` file. in the following way:

```
const ACTIVITY_LEVEL_OPTIONS = {
    sed: 1.2,
    light: 1.375,
    ...
}
```

You can access the values in the following way:

```
const tdee = (bmr * ACTIVITY_LEVEL_OPTIONS.sed) - 500
```

2024-01-21 03:02 UTC, atul-jalan commented on calculation.js
> +        var tdee = (bmr * sed) - 500;
So here's an example of why it's useful to declare constant variables.

a) You use the number 500 a dozen times throughout this code. Changing it means having to change it everywhere it's used.
b) It's not clear what the 500 value represents to someone reading this code. It takes a second to understand that it represents the daily calories gain/loss.

Think of a descriptive term for the `500` value, then declare at the top of the file, and use that variable everywhere.

2024-01-22 23:03 UTC, samardhk commented on calculation.js
> +function TDEE() {
total daily energy expenditure (so like total calories to consume everyday)

2024-01-22 23:06 UTC, samardhk commented on calculation.js
> +    var totalInches = (+feet * 12) + +inches;
i think it just converts it into a value so things like 5.5 can be added correctly and if letters are input itll say invalid

2024-01-25 00:54 UTC, atul-jalan approved these changes
lgtm. One change requested.

Also please audit your code and remove `var` everywhere and replace with `let` or `const`.

2024-01-25 00:54 UTC, atul-jalan commented on calculation.js
> +const activityleveloptions = {
When you declare constant value variables (meaning variables that represent some known static value), you want to distinguish them from other variables. For example, you should declare `centimeterperinch` in the following way:

```
const CENTIMETERS_PER_INCH = 2.54
```

Then, as you reference this variable in your code, it's clear that this is a constant value variable.

2024-01-25 02:38 UTC, merged